freebsd_instance:
  image_family: freebsd-12-2-snap
  cpu: 8
  memory: 16G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  only_if: $CIRRUS_BRANCH != 'svn_head'
  timeout_in: 120m
  install_script:
    - pkg install -y docproj
  test_script:
    - make all

